import LayoutSessionProvider from '@/provider/LayoutSessionProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import NavigationBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Auth - conline',
  description: 'Generated by create next app',
}

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {

  return (
    <html lang="en">
      <body>
        <LayoutSessionProvider>
          <NavigationBar></NavigationBar>
          <div className={inter.className}>{children}</div>
        </LayoutSessionProvider>
      </body>
    </html>
  );
}